<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\TalentShortlist.Domain\TalentShortlist.Domain.csproj" />
    <ProjectReference Include="..\TalentShortlist.Application\TalentShortlist.Application.csproj" />
    <ProjectReference Include="..\TalentShortlist.Infrastructure\TalentShortlist.Infrastructure.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>aitalentshortlist-local</UserSecretsId>
  </PropertyGroup>

</Project>
